require 'etherlite/commands/contract/event_base/decode_log_inputs'

module Etherlite::Contract
  class EventBase
    # The event type input definitions
    def self.inputs
      nil # To be implemented by sub classes
    end

    # The event type original name (before inflection)
    def self.original_name
      nil # To be implemented by sub classes
    end

    # The event type signature is used to build the topic when searching for specific events
    def self.signature
      @signature ||= begin
        input_sig = inputs.map { |i| i.type.signature }
        "#{original_name}(#{input_sig.join(',')})"
      end
    end

    # This method is used to decode incomming event logs
    def self.decode(_connection, _json)
      new(
        _json['blockNumber'].nil? ? nil : Etherlite::Utils.hex_to_uint(_json['blockNumber']),
        _json['transactionHash'],
        DecodeLogInputs.for(connection: _connection, inputs: inputs, json: _json)
      )
    end

    # The number for the block this event was generated in
    attr_reader :block_number

    # The hash for the transaction this event was generated by
    attr_reader :tx_hash

    # The event attributes as a hash, attributes are also available as methods
    attr_reader :attributes

    def initialize(_block_number, _tx_hash, _attributes)
      @block_number = _block_number
      @tx_hash = _tx_hash
      @attributes = _attributes
    end
  end
end
