name: Test and release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
        include:
          - ruby: '2.7'
            rubygems: '3.3.22'
    services:
      ganache:
        image: trufflesuite/ganache-cli:v6.12.2
        ports:
          - 8545:8545
        options: >-
          --health-cmd "nc -zv 127.0.0.1 8545"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 10

    env:
      GANACHE_HOST: 127.0.0.1
      GANACHE_PORT: 8545

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        rubygems: ${{ matrix.rubygems || '' }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

  release-please:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
